- hosts: localhost
  tasks:
  - name: create user johnny
    user: name=johnny state=absent
    become: yes
    become_method: sudo
  - name: install mc
    become: yes
    become_method: sudo
    yum: name=mc state=latest
  - name: install git
    become: yes
    become_method: sudo
    yum: name=git state=latest
  - name: github clone csicocd
    git:
     repo: https://github.com/kuku321/ciscocd.git
     dest: ~/ciscocd
     clone: yes
  - name: github clone petclinic
    git:
     repo: https://github.com/kuku321/spring-petclinic.git
     dest: ~/petclinic
     clone: yes
